DROP DATABASE IF EXISTS jdbc_ex;
CREATE DATABASE jdbc_ex;

DROP USER IF EXISTS 'scoula'@'%';
CREATE USER 'scoula'@'%' IDENTIFIED BY '1234';
GRANT ALL PRIVILEGES ON jdbc_ex.* TO 'scoula'@'%';
FLUSH PRIVILEGES;

USE jdbc_ex;

CREATE TABLE USERS (
  ID VARCHAR(12) NOT NULL PRIMARY KEY,
  PASSWORD VARCHAR(12) NOT NULL,
  NAME VARCHAR(30) NOT NULL,
  ROLE VARCHAR(6) NOT NULL
);

INSERT INTO USERS(ID, PASSWORD, NAME, ROLE)
VALUES
  ('guest', 'guest123', '방문자', 'USER'),
  ('admin', 'admin123', '관리자', 'ADMIN'),
  ('member', 'member123', '일반회원', 'USER');

SELECT * FROM USERS;
